# 基本站点设置
title: Pocket Flow
tagline: A 100-line LLM framework
description: Pocket Flow – Minimalist LLM Framework in 100 Lines, Enabling LLMs to Program Themselves

# 主题设置
remote_theme: just-the-docs/just-the-docs
search_enabled: true

# SEO 和站点地图
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-seo-tag:
  social:
    name: "Pocket Flow"
    twitter: "ZacharyHuang12"
    github: "the-pocket/PocketFlow"

# 导航
nav_sort: case_sensitive

# 辅助链接（显示在右上角）
aux_links:
  "View on GitHub":
    - "//github.com/the-pocket/PocketFlow"
    
# 配色方案
color_scheme: light

# 作者设置
author:
    name: Zachary Huang
    url: https://www.columbia.edu/~zh2408/
    twitter: ZacharyHuang12

# Mermaid 设置
mermaid:
  version: "9.1.3"
  config: |
    directionLR

# 标注设置
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  best-practice:
    title: Best Practice
    color: green
  
# 自定义导航
nav:
  - Home: index.md
  - GitHub: "https://github.com/ssvip9527/PocketFlow"
  - Discord: "https://discord.gg/hUHHE9Sa6T"